---
- name: Ubu Настройка файла /etc/hosts
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    insertafter: EOF
    line: '192.168.42.215 RedHat'
  when: "ansible_facts['os_family'] == 'Debian'"

- name: Orc Настройка файла /etc/hosts
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    insertafter: EOF
    line: '192.168.42.176 Debian'
  when: "ansible_facts['os_family'] == 'RedHat'"

# Настроить проверку наличия строки в файле с заменой содержимого. 