---
- name: Set Hostname
  ansible.builtin.include_tasks:
    file: tasks/hostname.yml

- name: Set DNS
  ansible.builtin.include_tasks:
    file: tasks/DNS.yml

#- name: Set Hosts
#  ansible.builtin.include_tasks:
#    file: tasks/hosts.yml

- name: Install Apps
  ansible.builtin.include_tasks:
    file: tasks/Appinstall.yml

- name: Handler restart Nginx
  ansible.builtin.include_tasks:
    file: handlers/main.yml

# Handler перезапуск Nginx